apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpa
rules:
  - apiGroups:
      - autoscaling.ocgi.dev
    resources:
      - generalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling.ocgi.dev
    resources:
      - generalpodautoscalers/status
    verbs:
      - update
  - apiGroups:
      - '*'
    resources:
      - '*/scale'
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resourceNames:
      - 'http:heapster:'
      - 'https:heapster:'
    resources:
      - services/proxy
    verbs:
      - get
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - custom.metrics.k8s.io
    resources:
      - '*'
    verbs:
      - get
      - list
  - apiGroups:
      - external.metrics.k8s.io
    resources:
      - '*'
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - "*"
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpa
subjects:
  - kind: ServiceAccount
    name: gpa
    namespace: kube-system
---
apiVersion: v1
data:
  cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURTVENDQWpHZ0F3SUJBZ0lKQU1wdmNlV1JTeFlxTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURIWmhiR2xrWVhSdmNsOWpZVEFnRncweU1UQTFNVFV4TXpNNE5EWmFHQTh5TWprMU1ESXlPREV6TXpnMApObG93S0RFbU1DUUdBMVVFQXd3ZFozQmhMWFpoYkdsa1lYUnZjaTVyZFdKbExYTjVjM1JsYlM1emRtTXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzloSG9ZRU1GbUFpNDhaalZuRHQvaG9xbnMKUXpTZEc3VUZoWk0wcmlneVRwSWVoU21PdUJKUHgvMXY2cjQwVXhqTTB3L1dQL2kzN1hRL3g3TDJSQkNaSGZwMwpOZHJ1alZaZkx3b2ZoZU80eG5BU2tHSlhFSGtWNllmakdRNUoxMHRSZVBsWjdKazBCelcwSTF1UnVEZERoNDAwClVvbUhvSThBVDFQOXI3a0I5dDBpaHdHMVZxNnVmdFRJUFNwandjNWtWMnRMT2VDLzR5eUQ5VjZwKytQMFVycWsKOFhLVE9mSUFzY3FFSjhSNWY1a1lhQVozTG0vem5wSk9ZYThNVDQ0T2twRTB5bnJvMDNLeXJhNGl2YTdKdy9FMQozZGtBL2s0YWZnTFYzNGNUdWhjRHhucmNpQUI4WCtNV2xGZW14MDlzeG9PR3dXaDJmZVpxTEY3bS9GbExBZ01CCkFBR2pnWVF3Z1lFd0NRWURWUjBUQkFJd0FEQUxCZ05WSFE4RUJBTUNCZUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUIKQlFVSEF3RXdVZ1lEVlIwUkJFc3dTWUlOWjNCaExYWmhiR2xrWVhSdmNvSVpaM0JoTFhaaGJHbGtZWFJ2Y2k1cgpkV0psTFhONWMzUmxiWUlkWjNCaExYWmhiR2xrWVhSdmNpNXJkV0psTFhONWMzUmxiUzV6ZG1Nd0RRWUpLb1pJCmh2Y05BUUVMQlFBRGdnRUJBSWN3T1A3MGx1Tjh3cW92K0NCdEt6ZmRPbkp1bStqSGpFNFIzSlljMVdQWkpKWG4KTWhsZFFIOStWNmNlblJrNWYzOHhSL2ZEdXhTODBqNUdzSzFhWUs5cU5NNGJhSUNYa1FQaVZ6WWd0NitOaWNMYQp3eWJuS0tNS0JncXhzeGZlMDdObTY2cFFRV2xxSlV4TEhSNWJ0WFpTVkk0amg5cjBjTmpBdDFVRXZNUGs3ZW9tCkIyQy9OSVIwaWVIVTMwaTZoU0ZhZW01NHp2NVVSVDNMeklNSHI3QTRwSi80SVVxRVlpWmJlSnEwdHZZaEVIR3QKTVFIcjdLYWZnUWhQd3hnSEFpUW95aEtybURxWUJyWWphWHNxUjNpaklrR1N5WVBiSXNVUnVkdjBHai9tQXRybApyVDNoSytGWjI5K0MvbDgrbTdVTEZ0VWdvMjFZUjNWMDlRWnRVYW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdllSNkdCREJaZ0l1UEdZMVp3N2Y0YUtwN0VNMG5SdTFCWVdUTks0b01rNlNIb1VwCmpyZ1NUOGY5YitxK05GTVl6Tk1QMWovNHQrMTBQOGV5OWtRUW1SMzZkelhhN28xV1h5OEtINFhqdU1ad0VwQmkKVnhCNUZlbUg0eGtPU2RkTFVYajVXZXlaTkFjMXRDTmJrYmczUTRlTk5GS0poNkNQQUU5VC9hKzVBZmJkSW9jQgp0VmF1cm43VXlEMHFZOEhPWkZkclN6bmd2K01zZy9WZXFmdmo5Rks2cFBGeWt6bnlBTEhLaENmRWVYK1pHR2dHCmR5NXY4NTZTVG1HdkRFK09EcEtSTk1wNjZOTnlzcTJ1SXIydXljUHhOZDNaQVA1T0duNEMxZCtIRTdvWEE4WjYKM0lnQWZGL2pGcFJYcHNkUGJNYURoc0ZvZG4zbWFpeGU1dnhaU3dJREFRQUJBb0lCQURvcU9KYStQYjBqR2pHcgpaT1IyYWp3RUFvYmlzWGt1a2NaYUVxM3ViYVBTL1lHa2VQYTJnOWc4bHdvTVQ4Z2JZTmNzU0FZSHFEdzdBcHk0Cm03SjlmV0toRXNnWG5WUHR5UDU1bjIvQlZmelYybnU0R0phRUZjV2w0UERRTmRSdjRVdm1CeEdVVGdqcjFZMnQKOUdLcTJUcytsUlhqNXhYYkwwaDNFRjRoMm5SQldpZmh2akRkMXdWY3FYQXZkakJSeUxhQmZMZVRrZWlxTVkzegpwWlRYMEpMNGFVMzQ4UmExaGRXMy93b21PSEVRbENkYVdIempQVUVXa2dWa0IxS1BnWHVDbExqcEdDMFY2MzI1Cmd2RVk5UzYwb2ZtK29hRWdTaURtSGdUMXcyRk43ZC9weVhvOTRYcHdGaG9wZk45VWRPaENsNjhVNG8zYTltdm0KZWRjdHNKRUNnWUVBOFE0c0JablF4UHVMYmdwOFZJaFhNWGRTaHJNOVNUOUo1dG15NVlUQk9rc2sxYllqYXpQYwpGRGY5ZmFXbDNMeCttczVjZXVoZ2dveThMMWxnMzdxVWVJbGdDeVdFNkcxQm53d2pybUo5L1lCLzZCaTNrZVlFCnljR1VJbXBtQ1BCOE50MUpXTHEzK0xSV0lkWnB6aDY4Z2pkZmhDSllwUVdwcFdkN3FjUk5MbmNDZ1lFQXlVUlcKMWJBMGJ1T21hbDdZamZtb1FHdEYzUjh6RW1WSXgrcCtHRFQzek5SZEhCQXkwUlRuUFZOdmlYTXk3OFFFTmVpNQpnWW5SbDA4cG51ZGlXQTQydmxNR1ljUjJUZlN1MEFQWUQ0ejc0SWpueDBIWkI3TkZ2UXUwcWdqUWFybzVPbEJLClFiaWtIODZJM3F4aFZCZFdIcUUxMGNmN1NWbCtQUURMa05kWC9NMENnWUJ2a2N5a1J2NE92aEpadXpheWRXeE4KODlsWmlRbzdwYlJSeWI3NFprcDg3Wnk5NFpCaEpONmU2UTlGb1c2MFRQWVlOcDB0TWZMQldkd2IyalZ4TjgxUwpRTnNZTGFSblkzSTA2QXgzd1JScFNabHAxazdZazJyeDZzdmlaZmFWK3FDelVCYUxuOWhZbnpjaWNEZ0djOGx5ClI2akk0cEMreUhFdG9ramxXWHNUbndLQmdRQ3FMY1NXanBUbkprb3lLdHhFdjlKS0ZlcE8yL0NkSDFMNDV3ZVQKaEVYNnhaMnMrdTFjNktYVnJ0VGlqYXVHSEdITEMycS9Zejc3QjQ2VHMrWHR1cWNES3NSOHFsZTE5cXhSYXM2bgo1M2VhRldpVmpOSHJ0dVBDdzBFUmZMNXRYK1MvcjkvNXpodklZU1JOMDhmQUNMTmkxc0RoRG8wbEtpeVpmRENqCjJkR21DUUtCZ1FDTk83ZDJkdWhVUzRtL1gxNWdkcFU5TlpwZXB1bzZtNGFRR0NIUnVnL01vKzdIVDA1NWVTR0MKUUswRFJpOCt1YkFQSXBQMlFOMU9WSkI1MEZSL1R5RTF3cldzRXZ0dHBaVFpIaWNDMnJUZVpsWWJUWGxtUEF5dwpOclJYUTFLKzNFNkVJV1BEWDVxZVlLcjFKM1pWMm5xSXFQRU9pSE9oREtWSHF4REhzbjEwenc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: gpa-secret
  namespace: kube-system
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpa
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpa-service
  template:
    metadata:
      labels:
        app: gpa-service
    spec:
      serviceAccountName: gpa
      containers:
        - args:
            - --tlscert=/root/cert.pem
            - --tlskey=/root/key.pem
            - --v=6
            - --port=443
          image: ocgi/gpa:latest
          imagePullPolicy: Always
          name: gpa
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /root
              name: gpasecret
      volumes:
        - name: gpasecret
          secret:
            secretName: gpa-secret
            items:
              - key: key.pem
                path: key.pem
              - key: cert.pem
                path: cert.pem

---
apiVersion: v1
kind: Service
metadata:
  name: gpa-validator
  namespace: kube-system
spec:
  selector:
    app: gpa-service
  ports:
    - port: 443
      targetPort: 443
